// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4623de8a-bc76-4f03-88f3-569fa8f0c583",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_73PCkoYQ2",
    "aws_user_pools_web_client_id": "p5rmr13m98qbc17oo1lsi9bm0",
    "aws_appsync_graphqlEndpoint": "https://6v7nr7v3hng35ibt5skkul3674.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fbdbcdsljnh65osgyyjlietmue"
};


export default awsmobile;
